export default {
  SET_STUDENTS_START: 'SET_STUDENTS_START',
  SET_STUDENTS_SUCCESS: 'SET_STUDENTS_SUCCESS',
  SET_STUDENTS_FAILURE: 'SET_STUDENTS_FAILURE',

  SET_COLUMNS_START: 'SET_COLUMNS_START',
  SET_COLUMNS_SUCCESS: 'SET_COLUMNS_SUCCESS',
  SET_COLUMNS_FAILURE: 'SET_COLUMNS_FAILURE',

  SET_ATTENDANCE_START: 'SET_ATTENDANCE_START',
  SET_ATTENDANCE_SUCCESS: 'SET_ATTENDANCE_SUCCESS',
  SET_ATTENDANCE_FAILURE: 'SET_ATTENDANCE_FAILURE',

  SET_RATE_START: 'SET_RATE_START',
  SET_RATE_SUCCESS: 'SET_RATE_SUCCESS',
  SET_RATE_FAILURE: 'SET_RATE_FAILURE',

  SET_UNRATE_START: 'SET_UNRATE_START',
  SET_UNRATE_SUCCESS: 'SET_UNRATE_SUCCESS',
  SET_UNRATE_FAILURE: 'SET_UNRATE_FAILURE',
};
